# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/build-debian-packages
name: Build Debian Packages

on: [push]

env:
  INPUT_SOURCE_DIR: ./releases/*/

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign